### ISSUE TITLE
Change data structure and field names

### ISSUE THREAD

**Issue by EGreg** [Intercoin/IncomeContract#17]
amountPaid should become amountClaimed

amountAllowedByManager should become amountPaid

remember that in UBI, someone can claim the maximum amount they are allowed, without manager, using claim() function

also Restrictions should be changed from locked (negative) to allowed (positive) … meaning it goes from 0 to maximum in *duration* seconds.

for example I can say… pay this guy $8000 over 8 weeks, gradually. In this case the maximum amount a manager can pay at any time is restricted to a triangle that starts when transaction is executed, and ends 8 weeks after that! The height of the triangle is $8000

I can define a second restriction, for example $5000 in 5 weeks, but gradual = false. It means I can send maximum of $5000 in 5 weeks, but it’s not gradual so I can send them all at once.

Usually we just add restrictions, to define the rate at which can be paid to this guy in a given time frame.

And maximum means the total amount that can be paid to the guy. It is like a restriction with 100 year time frame. So in fact you can remove maximum completely. Just use restriction functionality.

But again — restriction is not about locking tokens. Instead it is a restriction on the *rate of allowing tokens*.

1. Owner can fill IncomeContract, and appoint managers and set restrictions on the rate to pay recipients. Also may set the rate to accrue to recipients in UBI.
2. Then managers can PAY a recipient over time
3. And recipients can claim() up to the amountPaid + amountAccrued for UBI  !!

refactor and change the names.

**Comment by EGreg** [comment]
Also changed payed to paid in UBI everywhere… and the way it uses roles doesnt need keccak - just uint8

**Comment by artman325** [comment]
1. renamed vars

> amountPaid should become amountClaimed
> amountAllowedByManager should become amountPaid

and in the other fiels to be more consistents

2. 
please do separate issues for restrictions. and tell me what need to change from current behaviour. is current fucntional work as expected?

3. 
> and the way it uses roles doesnt need keccak - just uint8
for this i've created separeted issue #20
